<?php

define('FORMS_TRAINING_WELCOME_TITLE', 'Welcome to this Drupal Forms Training Tutorial');
define('FORMS_TRAINING_INSTRUCTIONS', '<p>In this Tutorial you will learn the skills to build and manage advanced form elements.</p><p> These are the following topics that we will cover, you can jump to any topic at any time:</p>');


/**
 * Implements hook_menu()
 */
function forms_training_menu(){
  $items['forms-training'] = array(
    'title' => 'Forms Training',
    'page callback' => '_forms_training_landing_page',
    'access callback' => TRUE, //Doesn't really matter to unrestrict access to this page
    'type' => MENU_CALLBACK
  );
  $items['forms-training/%'] = array(
    'title' => 'Forms Training - Exercise !number',
    'title arguments' => array('!number' => 1),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('_forms_training_form', 1),
    'access callback' => TRUE, //Doesn't really matter to unrestrict access to this page
    'type' => MENU_CALLBACK,
    'file' => 'forms_training.exercise.inc'
  );
  return $items;
}

/**
 * Page callback for the main page for this training
 */
function _forms_training_landing_page(){
  drupal_set_title('Forms Training');
  $content['welcome']['#markup'] = '<h2>'.FORMS_TRAINING_WELCOME_TITLE.'</h2>';
  $content['instructions']['#markup'] = FORMS_TRAINING_INSTRUCTIONS;
  $content['content_items']['#markup'] = theme('item_list', array(
    'items' => array(
      ''
    )
  ));
  $content['start']['#markup'] = l('Let\'s begin', 'forms-training/0');
  return $content;
}

/**
 * Forms training main form wrapper
 */
function _forms_training_form($form, &$form_state, $number){
  $form_state['exercise_number'] = $number;
  $form_def_name = '_forms_training_form_'.$number;
  if(function_exists($form_def_name)){
    $form_def_name($form, $form_state);
  }
  $form_exercise_def_name = 'forms_training_exercise_'.$number.'_form';
  if(function_exists($form_exercise_def_name)){
    $form['#suffix'] = '<strong>Your exercise form goes here:</strong>'.
      '<div style="border: 2px solid #090; min-height: 10px; padding: 10px;">'.
      drupal_render(drupal_get_form($form_exercise_def_name)).'</div>';
  }
  if($number){
    $form['previous'] = array(
      '#type' => 'submit',
      '#value' => 'Previous',
      '#name' => 'previous',
      '#submit' => array('_forms_training_form_previous_submit') 
    );
  }
  $form['next'] = array(
    '#type' => 'submit',
    '#value' => 'Next',
    '#name' => 'next',
    '#submit' => array('_forms_training_form_next_submit') 
  );
  return $form;
}

/**
 * Previous submit handler for the training form
 */
function _forms_training_form_previous_submit($form, &$form_state){
  $form_state['redirect'] = 'forms-training/'.($form_state['exercise_number']-1);
}

/**
 * Next submit handler for the training form
 */
function _forms_training_form_next_submit($form, &$form_state){
  $form_state['redirect'] = 'forms-training/'.($form_state['exercise_number']+1);
}

/*** FORMS TOPICS ***/

function  _forms_training_get_topics(){
  return array(
    'Basic Concepts',
    'Validation and Submit Handlers',
     
  );
}

/*** EXERCISE FORM DEFINITIONS ***/

/**
 * Exercise 0: Basic Concepts
 */
function _forms_training_form_0(&$form, &$form_state){
  $form['subtitle']['#markup'] = '<h2>Basic Concepts</h2>';
  $form['instructions']['#markup'] = '<div><p>Instructions:</p>'.
   '<p>This first exercise consists on recreate the following form to review basic concepts on creating form elements. If you need to, you can go to the Drupal <a target="_blank" href="http://api.drupal.org/api/drupal/developer!topics!forms_api_reference.html/7">Form API Reference</a></p>'.'</div>';
  $form['textfield'] = array(
    '#type' => 'textfield',
    '#title' => 'Textfield Input Sample',
    '#default_value' => 'A default value goes here'
  );
  $options = array('Option 1', 'Option 2', 'Option 3');
  $form['options'] = array(
    '#type' => 'radios',
    '#title' => 'Options Input Sample',
    '#options' => $options,
    '#default_value' => 2
  );
  $form['additional_1']['#markup'] = '<div>After creating the given form elements, try changing the options input into the following checkboxes</div>';
  $form['options_2'] = array(
    '#type' => 'checkboxes',
    '#title' => 'Checkboxes Input Sample',
    '#options' => $options,
    '#default_value' => array(1,2)
  );
}


/**
 * Exercise 1: Submit and validation handlers
 */
function _forms_training_form_1(&$form, &$form_state){
  $form['subtitle']['#markup'] = '<h2>Submit and Validation Handlers</h2>';
  $form['instructions']['#markup'] = '<div><p>Instructions:</p>'.
    '<p>Create a form similar to the following form (textfield and submit button) and add a validation handler that checks that the input in the checkbox has the string "Drupal Summit" (use strpos, regex or any other method you know) and submit handler that stores this into a variable named "forms_training_exercise_2_val". The content of the variable should display below once set:</p>';
  $form['variable_val']['#markup'] = '<div><strong>Variable content:</strong> <span style="color: #090">'.variable_get('forms_training_exercise_2_val', '').'</span></div>';
  $form['exercise_2'] = array(
    '#type' => 'textfield',
    '#title' => 'Name the event you are attending to',
    '#default_value' => '',
  );
  $form['exercise_2_submit'] = array(
    '#type' => 'submit',
    '#value' => 'Submit',
    '#validate' => array('_forms_training_form_1_validate'),
    '#submit' => array('_forms_training_form_1_submit'),
    '#suffix' => '<br />'
  );
}

/**
 * Exercise 1: Validation Handler
 */
function _forms_training_form_1_validate($form, &$form_state){
  if(strpos($form_state['values']['exercise_2'], 'Drupal Summit') === FALSE){
    form_error($form['exercise_2'], 'Text needs to contain "Drupal Summit"');
  }
}

/**
 * Exercise 1: Submit Handler
 */
function _forms_training_form_1_submit($form, &$form_state){
  variable_set('forms_training_exercise_2_val', $form_state['values']['exercise_2']);
}
