<?php

/**
 * Place your form code here
 */
function forms_training_exercise_0_form($form, &$form_state){
  $form = array();
  //Your code here
  return $form; 
}

/**
 * Place your form code here
 */
function forms_training_exercise_1_form($form, &$form_state){
  $form = array();
  //Your code here
  return $form; 
}

/**
 * Place your form code here
 */
function forms_training_exercise_2_form($form, &$form_state){
  $form = array();
  //Your code here
  return $form; 
}

/**
 * Place your form code here
 */
function forms_training_exercise_3_form($form, &$form_state){
  $form = array();
  //Your code here
  return $form; 
}

/**
 * Place your form code here
 */
function forms_training_exercise_4_form($form, &$form_state){
  $form = array();
  //Your code here
  return $form; 
}

/**
 * Place your form code here
 */
function forms_training_exercise_5_form($form, &$form_state){
  $form = array();
  //Your code here
  return $form; 
}

/**
 * Place your form code here
 */
function forms_training_exercise_6_form($form, &$form_state){
  $form = array();
  //Your code here
  return $form; 
}

/**
 * Place your form code here
 */
function forms_training_exercise_7_form($form, &$form_state){
  $form = array();
  //Your code here
  return $form; 
}

/**
 * Place your form code here
 */
function forms_training_exercise_8_form($form, &$form_state){
  $form = array();
  //Your code here
  return $form; 
}

/**
 * Place your form code here
 */
function forms_training_exercise_9_form($form, &$form_state){
  $form = array();
  //Your code here
  return $form; 
}
